module.exports = {
	inMarketOrder: [
		'Credits',
		'Bauxite',
		'Chalcopyrite',
		'Clay',
		'Coal',
		'Crude oil',
		'Gold ore',
		'Gravel',
		'Ilmenite',
		'Iron ore',
		'Limestone',
		'Lithium ore',
		'Quartz sand',
		'Rough diamonds',
		'Silver ore',
		'Aluminium',
		'Batteries',
		'Bricks',
		'Concrete',
		'Copper',
		'Electronics',
		'Fertilizer',
		'Fossil fuel',
		'Glass',
		'Gold',
		'Insecticides',
		'Jewellery',
		'Lithium',
		'Medical technology',
		'Plastics',
		'Scan drones',
		'Silicon',
		'Silver',
		'Steel',
		'Titanium',
		'Trucks',
		'Weapons',
		'Copper coins',
		'Drone wreckage',
		'Electronic scrap',
		'Fossils',
		'Giant diamond',
		'Maintenance kit',
		'Old tires',
		'Plastic scrap',
		'Roman coins',
		'Scrap metal',
		'Tech upgrade 1',
		'Tech upgrade 2',
		'Tech upgrade 3',
		'Tech upgrade 4',
		'Used oil',
		'Waste glass',
		'Attack dogs',
		'Elite force',
		'Gangster',
		'Private army',
		'Security staff',
		'Watch dogs'
	]
};
